# Generated by Django 6.1.2 on 2026-10-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0003_visitplan_planitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="has_captions",
            field=models.BooleanField(
                default=False, verbose_name="يتوفر نص مكتوب للمحتوى"
            ),
        ),
        migrations.AddField(
            model_name="booth",
            name="has_sign_language",
            field=models.BooleanField(
                default=False, verbose_name="يتوفر محتوى بلغة الإشارة"
            ),
        ),
    ]
