# Generated by Django 6.1.2 on 2026-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0004_booth_has_captions_booth_has_sign_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="booth",
            name="content_text",
            field=models.TextField(
                blank=True, verbose_name="النص المكتوب لمحتوى البوث"
            ),
        ),
    ]
