# Generated by Django 6.1.2 on 2026-10-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorprofile",
            name="show_captions",
            field=models.BooleanField(
                default=True, verbose_name="إظهار النص المكتوب مع المحتوى"
            ),
        ),
        migrations.AddField(
            model_name="visitorprofile",
            name="use_sign_language",
            field=models.BooleanField(
                default=False, verbose_name="عرض المحتوى بلغة الإشارة"
            ),
        ),
        migrations.AddField(
            model_name="visitorprofile",
            name="use_text_to_speech",
            field=models.BooleanField(
                default=False, verbose_name="تحويل أسئلتي المكتوبة إلى صوت"
            ),
        ),
    ]
